name: dotslash

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  check-files:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            abi: x86_64-unknown-linux-gnu
          - os: windows-2022
            abi: x86_64-pc-windows-msvc
          - os: macos-14
            abi: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15 # NOTE (aseipp): keep in-sync with the build.yml timeout limit

    name: check files
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          persist-credentials: false
      - name: Install DotSlash
        uses: ./.github/actions/install-dotslash
      - shell: bash
        run: |
          for x in $(ls -p buck/bin | grep -v / | grep -v BUILD | grep -v PACKAGE); do
            if ! dotslash "buck/bin/$x" --help; then
              echo "error: $x failed to run on ${{ matrix.abi }}"
              exit 1
            fi
          done
