buildscript = []
features = ["unstable_boringssl", "bindgen"]
extra_deps = [
    "third-party//bssl:crypto",
    "third-party//bssl:ssl",
    "third-party//bssl:decrepit",
    "third-party//bssl/rust:bssl-sys",
]
omit_deps = ["bssl-sys"]
cfgs = ["boringssl"]
